### ISSUE TITLE
Bug: "Reply" link set to white

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/memberlite#114]
If one selects another color scheme, e.q. Not So Primary, in the live preview the Reply link is rendered red, however once the customization is published, the link reverts to white.

**Moderator Link:**
https://memberlitetheme.com/forums/topic/the-reply-link-in-comments-is-rendered-white/

**Comment by kimcoleman** [comment]
This issue is resolved. I cannot replicate it in the latest release of Memberlite. Reply link now is a subtle default grey with white text and not influenced by color scheme.
