### ISSUE TITLE
User profile link in sidebar menu showing incorrect user name

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/memberlite#118]
With Paid Memberships Pro install and the Directory/Profile add on activated, when viewing a user's profile the sidebar menu displays the user being viewed's name in the Profile link instead of the current logged in user.
![member_directory_sidebar](https://user-images.githubusercontent.com/9744519/61957560-d2195280-afbf-11e9-8bbd-f356d4dbeef2.gif)

**Comment by ideadude** [comment]
Memberlite has logic to show all sibling pages in the sidebar. Technically the member profile page is a child of the membership account page. But we swap the page title based on the profile being shown. On other pages, it might say "Member Profile" there, and I'm not sure what would happen if you clicked the link.

We should find a way to hide the profile page from those sidebar menus.

I think this might be where we build that sidebar https://github.com/strangerstudios/memberlite/blob/dev/inc/extras.php#L447-L488

Aside: The logic for what kind of sidebar to choose is really complicated. Like figuring out if you are on the "blog" (a blog post, category, archive, etc).

I don't see a filter in that sidebar code I linked to, but maybe we can tap into wp_list_pages and if `! is_admin()` make sure we exclude the profile page if the child_of parameter is set. We can get the profile page from the $pmpro_pages global.

**Comment by kimcoleman** [comment]
Ok this is a two-fold issue. I think not showing all the child pages for Memberlite on the Membership Account page is a "good idea" but it isn't hard to change that per-page. We could discuss it as a feature of the theme but maybe its just a "filter" (don't show pmpro pages in `memberlite_nav_menu_submenu`).

The other one I think can be fixed in Member Directory and Profiles - don't filter the_title in menus/widgets?

**Comment by kimcoleman** [comment]
I'm going to close this as the issue of the sidebar in memberlite account pages has been updated - we no longer automatically show the page children menu in sidebars for nested Membership Account pages as part of this commit: https://github.com/strangerstudios/memberlite/commit/64645006f6b600a17373b5ef0c869914efb6b511

I have created an issue in the Member Directory and Profiles Add On repository for this where it could still deserve a fix: https://github.com/strangerstudios/pmpro-member-directory/issues/75
