### ISSUE TITLE
Breadcrumb Scheme; Support for Yoast Breadcrumbs

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite#121]
Option 1: Add the schema: 
https://developer.yoast.com/features/schema/pieces/breadcrumb/

Option 2: Support Yoast Breadcrumbs:
https://yoast.com/help/add-theme-support-for-yoast-seo-breadcrumbs/

**Comment by michaelbeil** [comment]
A [customer sent in the following](https://www.paidmembershipspro.com/forums/topic/site-breadcrumbs/): 

> In breadcrumbs, the site does not display the full path to a separate article.

> Breadcrumbs only by category (example – Home/Blog/Rubric)
> or directly to the article: Home / Postname
> 
> How to set up article breadcrumbs to show in full:
> Home/Blog/Rubric/Postname
> or
> Home/Rubric/Postname
> ?

**Describe the solution you'd like**
Show article breadcrumbs in full.

**Comment by kimcoleman** [comment]
I'm closing this ticket - I checked the Yoast stuff and it does still add the schema to the `yoast-schema-graph` in the head tag.

The customer requesting more structure in the breadcrumbs would need to write a custom function to override the default
