### ISSUE TITLE
CSS API Update for Google Fonts 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite#123]
See: https://developers.google.com/fonts/docs/css2

This new method updates the base URL for loading a Google font, allows you to string multiple font families in the single load (may or may not work), as well as sets better handling for variable  weights and what to do while font is loading (swap appears to be the best approach).

**Comment by andrewlimaza** [comment]
Updating this issue, WordPress.org now recommends to locally host the Google Fonts - https://wptavern.com/wordpress-org-strongly-urges-theme-authors-to-switch-to-locally-hosted-webfonts

**Comment by kimcoleman** [comment]
Closing this - we are now doing local webfonts.
