### ISSUE TITLE
Highlight current page item in the sidebar

### ISSUE THREAD

**Issue by peterjem** [strangerstudios/memberlite#129]
Hello,
          Is there any trick to highlight current page/post item in the sidebar?

Thanks

**Comment by peterjem** [comment]
Got it !
#secondary .widget_nav_menu .current_page_item a {
    color: blue
}

**Comment by kimcoleman** [comment]
I am glad you found a working solution. I am reopening this issue as we do want to make a theme style update to support a highlighted active page in this menu. 

I am exploring to make the link item bold for the active page. If you have other thoughts, perhaps applying the action or primary color as defined in the theme, please let me know.

**Comment by kimcoleman** [comment]
Added style in df46b91ed52e88f5ba577a377d85dbdd63ea1c83
