### ISSUE TITLE
Dark CSS and Comments 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite#139]
Need to recreate.

User reported that comments in the "Dark" mode are showing a light background and text is unreadable.

**Comment by JarrydLong** [comment]
I used this as a workaround for a client's ticket: 

```
.comment.depth-1.thread-alt, .comment .comment.alt, .comment, .pingback.even, .trackback.event {
background: initial !important;
}
```

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/memberlite/commit/136fad8b95d92d0da07e1ab20ba280d401a3f3e0
