### ISSUE TITLE
Right/Left Sidebar is shown below content when Content Archives is set to 'Show As Grid' 

### ISSUE THREAD

**Issue by dwanjuki** [strangerstudios/memberlite#168]
When the _Layout_ setting for an archive is set to _Right Sidebar_ or _Left Sidebar_ in the Customizer, changing the _Content Archives_ setting to _Show As Grid_ moves the sidebar below the content. The Columns Ratio is not applied on the Primary Container.

1. Go to Appearance > Themes > Customizer.
2. Customize an Archive Page eg. a Category Page.
3. Set Default Layout to Right Sidebar.
4. Set Content Archives to Show As Grid.

**Screenshots**
https://share.getcloudapp.com/NQu4BdjB

**Expected behavior**
Content Archives do not cover full width of the page. The sidebar is shown on the left or right of the content according to the selected sidebar layout setting.

**Isolating the problem**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Memberlite is the active theme.
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 6.1.1
Memberlite 4.5.4.1

**Comment by kimcoleman** [comment]
Jason made the decision to keep this sidebar in place - would people want to show things "after" the grid?

I'm up in the air on this decision. For now, though, as long as your blog page isn't set as the front page of your site (you have a separate "homepage" defined under Settings > Reading), you can hide the sidebar from the blog page like this:

1. Install and activate Memberlite Elements: https://wordpress.org/plugins/memberlite-elements/
2. Edit the "page" assigned as your "Posts page"
3. In the right sidebar, adjust the "Custom Sidebar" settings in the metabox. Change "Default Sidebar Behavior" to "Hide Default Sidebar".
4. Save the page.
<img width="1269" alt="Screenshot 2023-06-07 at 7 00 12 AM" src="https://github.com/strangerstudios/memberlite/assets/5312875/58bfcaec-23ab-4bf8-bc52-0e72d40d15a3">

Now the /blog page will not show the sidebar below the grid, but you can still leverage the sidebar on single posts pages.

Another method if you do not need sidebar content on single posts is to remove all widgets from the "Posts and Archives" widget location.
