### ISSUE TITLE
Escaping Issues: use esc_attr()

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#31]
Escaping missing in following, use [esc_attr()](https://developer.wordpress.org/reference/functions/esc_attr/):
* `memberlite_getColumnsRatio()` in following:
	* archive.php line 10
	* components/header/masthead.php line 22
	* forum.php line 10
	* header.php line 37 and 48
	* index.php line 8
	* mp_store.php line 15
	* page.php line 10
	* search.php line 8
	* sidebar.php line 11
	* single-testimonials-widget.php line 8
	* single.php line 8
	* templates/interstitial.php line 12
	* templates/landing.php line 11

**Comment by pbrocks** [comment]
https://github.com/strangerstudios/memberlite/pull/71
