### ISSUE TITLE
Escaping Issues: use esc_html()

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#32]
Escaping missing in following, use [esc_html()](https://developer.wordpress.org/reference/functions/esc_html/):
		* components/footer/site-info.php line 31: $back_to_top
		* components/header/meta-member.php line 17 and 20: preg_replace("/\@.*/", "", $current_user->display_name)

**Comment by pbrocks** [comment]
Addressed in [Pull Request](https://github.com/strangerstudios/memberlite/pull/79)
