### ISSUE TITLE
Escaping Issues: use wp_unslash()

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#33]
Escaping missing in following, use [wp_unslash()](https://developer.wordpress.org/reference/functions/wp_unslash/):
* components/header/masthead.php line 27 as
	* `$referrer = isset( $_GET['redirect_to'] ) ? esc_url_raw( wp_unslash( $_GET['redirect_to'] ); ) : null;`
* inc/admin.php line 23

**Comment by kimcoleman** [comment]
inc/admin.php no longer uses tabs so that code was removed here: https://github.com/strangerstudios/memberlite/commit/58858cd0a4f7830d098be7acfa49a5bed03240eb?diff=unified

**Comment by andrewlimaza** [comment]
Done - https://github.com/strangerstudios/memberlite/pull/83
