### ISSUE TITLE
Escaping Issues: use esc_url()

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#34]
Escaping missing in following, use [esc_url()](https://developer.wordpress.org/reference/functions/esc_url/):
	* functions.php line 132 `get_bloginfo( 'pingback_url' )`, line 240 `wp_logout_url()`, line 243 `wp_login_url()`, line 248 `wp_registration_url()`
	* inc\admin.php line 46, 56 `wp_customize_url`, line
	* template-tags.php
		* line 132, 134 `get_permalink`
		* line 247, 232 `comment_author_url`
	* components\header\masthead.php line 29 `$referrer` use `esc_url` instead of `esc_attr`
	* extras.php
		* line 134, 547, 564, 571, 667, 691, 816, 821 `get_permalink`
		* line 455 `$titlelink`
		* line 600, 678 `get_post_type_archive_link`
	* single-testimonials-widget.php line 15 `get_post_type_archive_link`

**Comment by justintadlock** [comment]
**inc/extras.php:**

* 604 - `get_permalink()`
* 800 - `get_comments_link()`
