### ISSUE TITLE
Escaping Issues: Use proper wp_kses family or other functions

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#35]
* Use proper [wp_kses()](https://developer.wordpress.org/reference/functions/wp_kses/) family or other functions
	* components/header/masthead.php line 44: `$memberlite_masthead_content`
	* components/post/content-audio.php line 36: `$memberlite_get_entry_meta_after`
	* components/post/content-image.php line 24: `$memberlite_get_entry_meta_after`
	* components/post/content-link.php line 20: `$memberlite_get_entry_meta_after`
	* components/post/content-quote.php line 32: `$memberlite_get_entry_meta_after`
	* components/post/content-single.php line 34: `$memberlite_get_entry_meta_after`
	* components/post/content-status.php line 28: `$memberlite_get_entry_meta_after`
	* components/post/content-video.php line 37: `$memberlite_get_entry_meta_after`
	* components/post/content.php line 42: `memberlite_get_entry_meta`
	* components/post/entry-header.php line 35: `memberlite_get_entry_meta`
	* inc/extras.php
		* line 242 `$term_description`
		* line 250 `$post_type->labels->name`

**Comment by ideadude** [comment]
Fixed:
https://github.com/strangerstudios/memberlite/commit/0bc89290232a7a744ea20c999f61ab9438195344
