### ISSUE TITLE
Anonymous functions

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#38]
* You cannot use anonymous functions. Although using anonymous function only affects PHP version 5.2 or less, the themes in WordPress.org repo still needs to support it. Check `functions/customizer.php` lines 544 and 550. Make mother function and call it there rather than using it anonymously.
	* `inc/customizer.php` line 641 and 647
	* `inc/deprecated.php` line 50

**Comment by justintadlock** [comment]
.ORG allows anonymous functions.  Your theme simply must either have a fallback, not execute the code, or it must do a PHP version check for PHP 5.3.0+ and switch back to the previous theme upon activation.

Basically, you can't have a PHP error for users running PHP 5.2.

I do agree about simply making named functions though if that's the only thing keeping you from PHP 5.2 support.

**Comment by ideadude** [comment]
I swapped out the anonymous functions in customizer.php here https://github.com/strangerstudios/memberlite/commit/94c4a8c40256192cc314e098292f61f2b1d618ec

In deprecated I updated it to use create_function if on PHP 5.2 https://github.com/strangerstudios/memberlite/commit/444b06a75d1c64a2008b5639a7ac7b28eb88ee2b
