### ISSUE TITLE
Prefixing

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#41]
* Class Prefix
     * Class prefixes should be `Memberlite_` if you follow WordPress Coding Standards.
     * Check following class names
          * memberlite_Customize
          * comment_walker
          * pings_walker
          * WP_Widget_Recent_Posts_Thumbnails
     * You need to maintain consistency
* Function Prefixes
     * Need to make function prefixes theme slug in following:
               * integrations\woocommerce.php line 39 and 42
     * More info: http://themereview.co/prefix-all-the-things/
* Image names prefix
	* Prefix missing in add_image_size in functions.php lines 91 to 94
	* More info: http://themereview.co/prefix-all-the-things/

**Comment by justintadlock** [comment]
`$fontawesome_icons` in `inc/defaults.php` should be prefixed as well.

**Comment by justintadlock** [comment]
Make sure to prefix action and filter hooks as well.

On line 63 of `inc/widgets.php`:

```
apply_filters( 'widget_posts_args',
```

**Comment by ideadude** [comment]
Done except the image sizes here:
https://github.com/strangerstudios/memberlite/blob/memberlite-elements/functions.php#L175-L178

Need to figure out what the name change will affect in the code and css. Not sure if we should use memberlite- or memberlite_ I'll leave it up to @kimcoleman

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/memberlite/commit/42f53380466593ef3569b71df83f995875253d4d

**Comment by justintadlock** [comment]
Just noting that I personally prefer hyphens for things like image sizes and script/style handles, which looks like y'all have used.
