### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#42]
Images in screenshot licenses
* Need to mention license of the images used in screenshot
* Since they are from WordPress demo data, you can just mention same in the readme file

**Comment by justintadlock** [comment]
The license and copyright info for the images within `/images` need to be mentioned in the readme.

Also, if there's code from WooCommerce, bbPress, or any third-party plugin, you'd want to include their license as well.  I'm just now looking at the code, but I'm seeing at least two templates that are likely largely copied from those plugins.

**Comment by justintadlock** [comment]
The Font Awesome CSS is licensed under the MIT license.  Since this is included in the theme, you'll want to list that in your readme as well.  Note that this is separate from the font license.

**Comment by ideadude** [comment]
Updated some in this commit. https://github.com/strangerstudios/memberlite/commit/966106f0656a99096783aa98cf38c02dcac17446

@kimcoleman let me know what CSS frameworks we may need to mention in here.

**Comment by kimcoleman** [comment]
CSS "framework" is the Foundation grid by Zurb - although I have modified it. 

See: https://foundation.zurb.com/grid.html

**Comment by ideadude** [comment]
I think we got them all now.
