### ISSUE TITLE
Google font enqueue

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#43]
* The way you have enqueued google font in `functions.php` lines 40-46 is not ideal
* Check http://themeshaper.com/2014/08/13/how-to-add-google-fonts-to-wordpress-themes/ on how to enqueue google font properly
* For google font rather than registering you need to enqueue via wp_enqueue

**Comment by justintadlock** [comment]
I just want to note that this line should use `wp_enqueue_scripts` instead of `wp_print_styles`:

```
add_action('wp_print_styles', 'memberlite_load_fonts');
```

**Comment by ideadude** [comment]
Review with @kimcoleman 

Code from the Sketch theme in the linked tutorial is here: https://themes.svn.wordpress.org/sketch/1.2.4/functions.php

**Comment by ideadude** [comment]
We should add a non-Google Font option (Arial?) to the dropdown list of fonts.

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/memberlite/commit/19a635552d0387aac19d0e4d5364d7816a5560ff#diff-78cd5aa3783a74555c9938a2a81d01c6
