### ISSUE TITLE
JS Issue

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#46]
* Check your theme with [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin. When you click on reply button in comment it shows error 
`Error: Syntax error, unrecognized expression: http://themereview.dev/2017/03/12/human-faces-in-web-design/?replytocom=5#respondhttp://themereview.dev/wp-includes/js/jquery/jquery.js?ver=1.12.4 line 2`

**Comment by ideadude** [comment]
Our JS to detect clicks on hash hrefs was breaking on the reply links.

Fixed here https://github.com/strangerstudios/memberlite/commit/b1b23abf79df237fac82cd91d097bed8909984be
