### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#47]
* Blockquote right and left align css missing. See the screenshot 
![blockquote](https://user-images.githubusercontent.com/9452203/35599592-6866160c-05f7-11e8-9820-40b112bdb292.png)
* Post With Long Title. See the attached screenshot
![long-title](https://user-images.githubusercontent.com/9452203/35599597-6f89971a-05f7-11e8-9abe-88cb353e9feb.png)

**Comment by kimcoleman** [comment]
@sakinshrestha can you share the post content for the right and left align blockquotes as in your screenshot. I've tested using the blockquote element and the right or left align text button in the visual editor and it is working. Is this using the `text-align: right` CSS or the `alignright` class on the blockquote?

I've repaired the word wrap issue for long titles / long words in titles.

**Comment by sakinshrestha** [comment]
@kimcoleman : ok that left and right align in blockquotes is not that good. as you have see the text and the width is so tight. You might want to check this demo for example, it’s nice https://twentysixteendemo.wordpress.com/style-guide/

**Comment by kimcoleman** [comment]
Improved right and left align block quotes here:
https://github.com/strangerstudios/memberlite/commit/36dd05ccf7ddc552fe57a5a2f2708c642a6edf1a
