### ISSUE TITLE
Recommendation: Menu location naming

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#48]
This is a bit of a pet-peeve of mine, but it's also about making a good user experience.  You've named your theme menu locations as:

```
register_nav_menus( array(
		'primary' => __('Primary Menu', 'memberlite'),
		'member' => __('Member Menu', 'memberlite'),
		'member-logged-out' => __('Member Menu - Logged Out', 'memberlite'),
		'meta' => __('Meta Menu', 'memberlite'),
		'footer' => __('Footer Menu', 'memberlite'),
	));
```

The term "Menu" is actually inaccurate.  These are technically "locations" that you're registering.  I'd rather simply see `Primary`, `Primary Location`, `Primary Area`, etc.  Give it a test from a user's point of view in the admin.

And, yes, the WP devs screwed up when they named this function `register_nav_menus()` because it doesn't register nav menus at all. :)

**Comment by ideadude** [comment]
Updated here https://github.com/strangerstudios/memberlite/commit/3c4785643dd01fe00fee556022caea29b167728c thanks
