### ISSUE TITLE
Translation: General

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#49]
In `inc/admin.php` on line 12, you need to internationalize the menu and page title:

```
add_theme_page( 'Memberlite Documentation and Support', 'Memberlite Guide', 'edit_theme_options', 'memberlite-support', 'memberlite_support' );
```

And, the `aria-label` on line 28:

```
<div id="wpbody-content" aria-label="Main content" tabindex="0">
```

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/memberlite/commit/c68f2b4e9d37ca23eaaad13cecb666f75f3ddcf2 thanks
