### ISSUE TITLE
PHP Strict Standards Warning

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/memberlite#5]
The definition of start_el() in [template-tags.php](https://github.com/strangerstudios/memberlite/blob/dev/inc/template-tags.php#L248) triggers a PHP warning: 
`PHP Strict Standards:  Declaration of comment_walker::start_el() should be compatible with Walker_Comment::start_el(&$output, $comment, $depth = 0, $args = Array, $id = 0) in /webroot/wp-content/themes/memberlite/functions.php on line 268`

**Comment by jmcclellan** [comment]
I'll be using this theme as a parent and noticed this error so I went to fix it and create a pull request and realized it's already been fixed. Should be resolved with commit e5111b56
