### ISSUE TITLE
Unnecessary permissions check

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#50]
This bit of code in the `memberlite_support()` function in `inc/admin.php` shouldn't be necessary:

```
if( !function_exists( 'current_user_can' ) || ( !current_user_can( 'edit_theme_options' ) && !current_user_can( 'member_lite_options' ) ) ) {
		die( __( 'You do not have permissions to perform this action.', 'memberlite' ) );
	}
```

WP will already correctly check the `edit_theme_options` cap via your `add_theme_page()` registration earlier.  I'm not sure what the `member_lite_options` cap is.  That check shouldn't be there anyway.

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/memberlite/commit/71a167655b20db475f8daf9b49027f5188fe625a thanks
