### ISSUE TITLE
Sanitizing: Customizer setting JS callback

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#51]
Why is every customizer setting in `inc/customizer.php` set to this?

```
'sanitize_js_callback' => array('memberlite_Customize', 'memberlite_sanitize_js_callback'),
```

There's really no reason to set the `sanitize_js_callback` callback unless you need the data to take on a special form as it comes from the database into the customizer JS.

**Comment by ideadude** [comment]
Not sure. I probably didn't know it defaulted to esc_js anyway. Maybe I thought it was better for review to be explicit about the sanitization.

This commit fixed an issue with the method name: https://github.com/strangerstudios/memberlite/commit/708cdabd30994bb6187242e7af70c359b0710afb

I think I'll leave these in for now, but it is redundant with the defaults.

Do you think this has a strong chance to count as a notch against us in code review?

**Comment by justintadlock** [comment]
Honestly, I don't think most theme reviewers would give it a second glance. :)  It wouldn't count against you in a theme review on .ORG or anything.
