### ISSUE TITLE
Global $post for body class

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#52]
In `inc/extras.php` on line 29, I'm seeing a call to `$post` here:

```
global $post, $memberlite_defaults;
```

That doesn't seem to be in use and can be removed.  

Side note:  I'd never rely on `$post` unless within The Loop.  Outside of The Loop, you should check `get_queried_object()`.

**Comment by ideadude** [comment]
Fixed. Thanks. https://github.com/strangerstudios/memberlite/commit/5975ce0dc99de25708d5279fda01070c40ab2a28

We did use global post in a few places where get_queried_object was better. Should have those fixed up too.
