### ISSUE TITLE
Archive titles and descriptions

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#53]
In the `memberlite_page_title()` function in `inc/extras.php`, .ORG will require that you use `the_archive_title()` and `the_archive_description()` (or their `get_*()` counterparts) for the archive title and descriptions.  This goes for any type of archive.  If you output the archive title or description, it must come from those functions.

The reason for this is simply that plugins need a way to hook in and overwrite the output.

**Comment by ideadude** [comment]
Fixed. Thanks. https://github.com/strangerstudios/memberlite/commit/20403d3d74879bc80998debeadda5f5ea4969c73
