### ISSUE TITLE
"Is blog" function

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#54]
In `inc/extras.php` on line 418, there are scenarios where this wouldn't hold true:

```
/**
 * Are we on a "blog" page?
 */
function memberlite_is_blog() {
	$is_blog = ( is_home() || is_singular('post') || ( is_archive() && !is_post_type_archive() ) );

	$is_blog = apply_filters( 'memberlite_is_blog', $is_blog );

	return $is_blog;
}
```

`is_archive()` counts custom taxonomies too.  You might try adding an `! is_tax()` in there.

**Comment by ideadude** [comment]
Added. Thanks. https://github.com/strangerstudios/memberlite/commit/7e613a8520ea7380eba6d17321722ee45d0ca063
