### ISSUE TITLE
Register widgets on widgets_init

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#55]
In `inc/widgets.php`, the widget is simply registered from the file:

```
register_widget( 'WP_Widget_Recent_Posts_Thumbnails' );
```

This code should be wrapped into a callback function and executed on the `widgets_init` hook.

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/memberlite/commit/09c3dca06344204e4c286f378ce49aa15d43256a
