### ISSUE TITLE
Recommended: Less PHP code in templates

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#57]
Where possible, I like to see themes remove as much PHP logic from their templates as they can.  One of the great things about WP themes is that they allow DIY users who might know a bit of HTML to tinker with the code.  But, when they see a lot of PHP in a theme template, it can get confusing and/or be easy to break.

For example, this bit of code in `header.php`:

```
<?php
	$template = get_page_template();
	if(
		!is_page_template('templates/fluid-width.php') &&
		!is_404() &&
		( !is_front_page() || ( is_front_page() && !empty( $template ) && ( basename( $template ) != 'page.php' ) || 'posts' == get_option( 'show_on_front' ) ) )
	) { ?>
	<div class="row">
<?php } ?>
```

Personally, I'd wrap up the conditional bit of the code into a function called `memberlite_display_row()` and use it like so:

```
<?php if ( memberlite_display_row() ) : ?>

	<div class="row">

<?php endif; ?>
```

That's simpler, cleaner, and harder to break.

I'd also say that this is beneficial for child theming as well because:

1. If overwriting `header.php`, there's less chance that a parent theme update will introduce a breaking change since the logic code is tied into a function and not the template.
2. If a child theme author wanted to display the `<div class="row">` on another page, you could provide a filter hook within your function.  And, there'd be no need to overwrite the template in that scenario.

Anyway, this is something I often mention to theme authors.  If you can, remove as much PHP code from your templates as you can.

**Comment by ideadude** [comment]
Good feedback. We will keep this in mind when updating or refactoring code.
