### ISSUE TITLE
Double or triple images

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#58]
On archive-type pages, there's potentially double or even triple of the same images shown on the page as you'll see in the below screenshots.  I'll try to break this all down to clarify.

**Double image:**

The "Featured Images on Index/Archives" option in the customizer has an option named "Show Banner or Thumbnail" (the default option).  However, the actual value is `show_both` and is used to show both the featured image as a banner **AND** thumbnail.  The **OR** is confusing in the text.

I'm not sure what scenarios "or" would ever crop up since you usually can't have one without the other.

![double-image](https://user-images.githubusercontent.com/1816309/35691971-93b55b4e-073f-11e8-8721-a7076e1daf14.png)

**Triple image:**

Given the above double image, this can also be turned into a triple image issue if the user elects to "Show Post Content" for the "Content Archives" option in the customizer.  You get the triple image effect when the user also shows the image in their post content.

Given that you have options to choose whether to show the featured image, this may not be an issue.  I just wanted to make sure that you were aware of it.

![triple-image](https://user-images.githubusercontent.com/1816309/35691981-99c933c0-073f-11e8-9ef3-4ee42f3ec83e.png)

**Comment by kimcoleman** [comment]
We've updated the setting to say "Show Banner and Thumbnail" and are now only showing that setting option if the Multiple Post Thumbnails plugin is installed and activated.

This should help to combat any cases where the same image is displayed twice or thrice.

https://github.com/strangerstudios/memberlite/commit/e4fb83576861e4dc32beb792d728a5f785ed040b

**Comment by ideadude** [comment]
We have decided to address this for v4.1 (or via a memberlite-elements update)

Roughly, when "show banner and thumbnail" is set in the customizer featured image option, we won't show the featured image as the banner unless the "show as banner" option is checked on the edit post page (by the featured image). If "show as banner" is checked here, we will NOT show the featured image as the thumbnail.

So...

When rendering the archive view of a post and the "show banner and thumbnail" global option is set:

1. The banner is going to be first the specified banner image or if the "show as banner" option is checked on the featured image, use that as the banner.

2. The thumbnail image is the featured image unless the "show as banner" option is checked.
