### ISSUE TITLE
Styling: Uneven spacing in blockquotes

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#59]
For blockquotes, the bottom spacing doesn't match up with the top spacing.  See screenshot below.

![blockquotes](https://user-images.githubusercontent.com/1816309/35692589-649a04b6-0741-11e8-9e89-efebc22092d8.png)

**Comment by ideadude** [comment]
I personally like the extra padding at the bottom of the blockquote, but I'm pretty sure now I'm the exception here. So we made it even. Also fixed the marins to match p tags.
