### ISSUE TITLE
Styling: Quote tag

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#60]
The `<q>` tag is an inline element.  It can appear in the middle of a paragraph or even in the middle of the sentence.

The ideal way to style it is to simply make sure it has normal quotation marks.

Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q

"Developers, developers, developers..." is the quote from the screenshot below.  But, you can't gather that from the style.

![q-tag](https://user-images.githubusercontent.com/1816309/35692652-86ca0c7a-0741-11e8-9991-54782bef113a.png)

**Comment by kimcoleman** [comment]
I've removed the custom styling on the q tag specifically in this file:

https://github.com/strangerstudios/memberlite/blob/memberlite-elements/style.css
