### ISSUE TITLE
Customizer: Sanitizing select controls/settings

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#61]
Note that this is a recommendation only, but one I highly recommend.

When you have a `select` control in the customizer, you're using `sanitize_text_field` to go along with the setting.  I'm going to present an alternative, which is even safer than simply sanitizing.  Instead, we're going to use whitelist validation.

Here's a customizer control + setting from your `inc/customizer.php` file:

```
$wp_customize->add_setting(
	'columns_ratio',
	array(
		'default' => $memberlite_defaults['columns_ratio'],
		'type' => 'theme_mod',
		'capability' => 'edit_theme_options',
		'santize_callback' => 'sanitize_text_field',
		'sanitize_js_callback' => array('memberlite_Customize', 'memberlite_sanitize_js_callback'),
		'transport' => 'refresh',
	)
);
$wp_customize->add_control(
	'columns_ratio',
	array(
		'label' => __( 'Columns Ratio - Primary', 'memberlite' ),
		'section' => 'memberlite_theme_options',
		'type'       => 'select',
		'choices'    => array(
			'6-6' => __( '6x6', 'memberlite' ),
			'7-5' => __( '7x5', 'memberlite' ),
			'8-4' => __( '8x4', 'memberlite' ),
			'9-3' => __( '9x3', 'memberlite' ),
			'10-2' => __( '10x2', 'memberlite' ),
			'11-1' => __( '11x1', 'memberlite' ),
		),
		'priority' => 24
	)
);
```

The first thing I'm going to do is take that `choices` array and turn it into a standalone function like so:

```
function memberlite_get_columns_ratio_choices() {

	return array(
		'6-6' => __( '6x6', 'memberlite' ),
		'7-5' => __( '7x5', 'memberlite' ),
		'8-4' => __( '8x4', 'memberlite' ),
		'9-3' => __( '9x3', 'memberlite' ),
		'10-2' => __( '10x2', 'memberlite' ),
		'11-1' => __( '11x1', 'memberlite' )
	);
}
```

Then, I'm going to make a validation function:

```
function memberlite_validate_columns_ratio( $value ) {
	global $memberlite_defaults;

	return in_array( $value, memberlite_get_columns_ratio_choices() ) ? $value : $memberlite_defaults['columns_ratio'];
}
```

Then, your customizer code becomes:

```
$wp_customize->add_setting(
	'columns_ratio',
	array(
		'default' => $memberlite_defaults['columns_ratio'],
		'type' => 'theme_mod',
		'capability' => 'edit_theme_options',
		'santize_callback' => 'memberlite_validate_columns_ratio',
		'sanitize_js_callback' => array('memberlite_Customize', 'memberlite_sanitize_js_callback'),
		'transport' => 'refresh',
	)
);
$wp_customize->add_control(
	'columns_ratio',
	array(
		'label' => __( 'Columns Ratio - Primary', 'memberlite' ),
		'section' => 'memberlite_theme_options',
		'type'       => 'select',
		'choices'    => memberlite_get_columns_ratio_choices(),
		'priority' => 24
	)
);
```

Of course, that can be a lot of work.  However, it can make your code much more flexible in the future by giving you more choices without having to do big refactors later.

------

Another options for sanitizing select callbacks is the simpler method proposed by the Theme Review Team: https://github.com/WPTRT/code-examples/blob/master/customizer/sanitization-callbacks.php#L262-L288

One thing to note is that the `setting` and `control` ID **must** match for this to work, which seems to be the case with your theme.

**Comment by ideadude** [comment]
Good idea. Went with the general sanitize_select function from the TRT example.

Patched here: https://github.com/strangerstudios/memberlite/commit/d149673dc9289febbc7cfab554a4edf9e8ca6715
