### ISSUE TITLE
Customizer: No need to set defaults

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#62]
When adding panels, sections, controls, or settings, you don't need to set the `edit_theme_options` capability.  It's the default for the customizer:

```
'capability' => 'edit_theme_options',
```

You also don't have to set the `theme_mod` type for settings, which is also the default:

```
'type' => 'theme_mod',
```

Unless you just really want to do this for additional clarity, these are unnecessary.  It could help you cut back on some of your customizer code.

**Comment by ideadude** [comment]
https://github.com/strangerstudios/memberlite/commit/7e123737f01b0cbb3ea9e29003238fbc7d446da0
