### ISSUE TITLE
Customizer: Sanitizer callbacks misspelled

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#63]
There are multiple misspellings of `sanitize_callback` and `sanitize_js_callback` in `inc/customizer.php`.  They are spelled as:

```
'santize_callback'

'santize_js_callback'
```

Note the missing `i` between `n` and `t`.  You'll want to open your text editor and do a search/replace to get the spelling right.

**Comment by ideadude** [comment]
https://github.com/strangerstudios/memberlite/commit/0c8a5f4742d7df35f9d59234cbf725bc29118216
