### ISSUE TITLE
Escaping: Custom CSS output

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#64]
In `inc/customizer.php`, all of the theme mods that are output in the `header_output()` method need to be escaped.  This includes CSS that is generated via the `generate_css()` method.

`esc_html()` should be sufficient for escaping things here.

**Comment by ideadude** [comment]
https://github.com/strangerstudios/memberlite/commit/90f625819d6444961fc1533d7c9ecb793d0f57df

The generate_css function has a parameter to echo or return the value. When echoing, it uses esc_html. I also added esc_html around vars in the other css being echo'd there.
