### ISSUE TITLE
style.css "Author" header

### ISSUE THREAD

**Issue by justintadlock** [strangerstudios/memberlite#66]
I'm not positive that this Author line will be allowed like this:

```
Author: kimannwall, strangerstudios
```

Generally speaking, the field is expected to be a single author.  However, it's also just a plain text string.  It's something you may want to run by the `#themereview` channel on WP Slack.  I don't think I've ever run across this scenario.

Note that this does not correspond to usernames on .ORG like with a plugin's `readme.txt`.

**Comment by ideadude** [comment]
Thanks. Went with Stranger Studios, which seems to be the expected type of value for themes.
