### ISSUE TITLE
Some BuddyPress buttons are invisible.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/memberlite#67]
On the elements branch, with a fresh install of BuddyPress (and PMPro BuddyPress).

I activated user groups and created a new one. BuddyPress redirects me to the front end to finish setting up the group.

The buttons at the bottom of their forms are white text on white background with a gray border.

Not sure if this is a conflict with our theme css or something else.

**Comment by kimcoleman** [comment]
I've added BuddyPress styling to the memberlite-elements branch that resolves this issue.

https://github.com/strangerstudios/memberlite/blob/memberlite-elements/css/buddypress.css
