### ISSUE TITLE
Gutenberg Compatibility: Featured Image in Banner Area

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/memberlite#69]
With Gutenberg active we lose the checkbox in Postmeta that allows you to show the Featured Image in the Banner area. Screencast illustrates the steps to recreate the issue.

Screencast of Banner [http://take.ms/plSyKs](http://take.ms/plSyKs)

**Comment by kimcoleman** [comment]
We are not planning to continue to support that setting for the featured image in the post so I am going to close this. For now we can recommend people use the Multi Post Thumbnails plugin with Memberlite Elements to have a banner image of their choice.
