### ISSUE TITLE
"Blank" Landing Page Template

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite#70]
A user requested that we consider adding a menu-free template (maybe remove more header/footer content) for landing pages.

**Comment by andrewlimaza** [comment]
I've worked on something for this - https://github.com/strangerstudios/memberlite/pull/82

This will create a completely blank page without menu or footer links :)

**Comment by kimcoleman** [comment]
Done in: https://github.com/strangerstudios/memberlite/commit/4cb42c1d20a794fb075c39634b81be8d220e619f
