### ISSUE TITLE
esc_html now blocking the icon html from rendering in "Back to Top" link

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite#86]
Recent updates to esc_html on the $back_to_top link have broken the appearance of the chevron-up icon as pictured. Propose to switch to a CSS-based approach OR use wp_kses with some allowed html filters (suggested by Paul).

<img width="1099" alt="screen shot 2018-07-19 at 8 00 56 am" src="https://user-images.githubusercontent.com/5312875/42942956-7cbd5080-8b2f-11e8-8adf-2129aa9a818a.png">

https://github.com/strangerstudios/memberlite/blob/memberlite-elements/components/footer/site-info.php#L34-L39

**Comment by pbrocks** [comment]
Can confirm that this works properly:

`	<?php if ( ! empty( $back_to_top ) ) { ?>
		<div class="large-2 columns text-right">
		<?php
			$back_to_top = apply_filters( 'memberlite_back_to_top', __( '<i class="fa fa-chevron-up"></i> Back to Top', 'memberlite' ) );
			$allowed_html = memberlite_allowed_html();
			$sanitized_string = wp_kses( $back_to_top, $allowed_html );
		if ( ! empty( $sanitized_string ) ) {
			echo '<a class="skip-link btn" href="#page">' . $sanitized_string . '</a>';
		}
		?>
		</div>
	<?php } ?>`
`function memberlite_allowed_html() {
	$allowed_tags = array(
		'i' => array(
			'class'  => array(
				'fa',
			),
		),
	);
	return $allowed_tags;
}
`


Reference: [WordPress Basic Allowed HTML for wp_kses](https://wp-mix.com/wordpress-basic-allowed-html-wp_kses/)

**Comment by pbrocks** [comment]
This also works:
```
function memberlite_allowed_html() {
	$allowed_tags = array(
		'i' => array(
			'class'  => array(),
		),
	);
	return $allowed_tags;
}
```
But this does not:
```
function memberlite_allowed_html() {
	$allowed_tags = array(
		'i' => array(),
	);
	return $allowed_tags;
}
```

**Comment by ideadude** [comment]
```
		<?php
			$back_to_top = apply_filters( 'memberlite_back_to_top', '<i class="fa fa-chevron-up"></i>' . esc_html__( 'Back to Top', 'memberlite' ) );
		if ( ! empty( $back_to_top ) ) {
			echo '<a class="skip-link btn" href="#page">' . $back_to_top . '</a>';
		}
		?>
```

**Comment by ideadude** [comment]
tab are off on that code, but you get the idea. Let's avoid kses/allowed html stuff if at all possible. On content/body/description fields we can't, but we can here.

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/memberlite/commit/9fd685fe568dd9b552ff7ccdac9797865a294ac2
