### ISSUE TITLE
HTML span class showing on front end for post navigation

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite#89]
Resolve esc_html issue where code is displaying on the front end per screenshot below for function memberlite_paging_nav.

https://github.com/strangerstudios/memberlite/blob/memberlite-elements/inc/template-tags.php#L21-L47

<img width="472" alt="screen shot 2018-07-25 at 11 17 06 am" src="https://user-images.githubusercontent.com/5312875/43210260-9867c0be-8ffc-11e8-88a1-8c31bf772979.png">

**Comment by kimcoleman** [comment]
Should implement a fix like this:
https://github.com/strangerstudios/memberlite/commit/9fd685fe568dd9b552ff7ccdac9797865a294ac2

**Comment by pbrocks** [comment]
@kimcoleman I'm not seeing what you have above. This link
http://take.ms/nRMkq is a screencast that shows the Dev branch to render properly, but it also shows that Member Elements branch is (12 commits) behind.

**Comment by kimcoleman** [comment]
We have not merged the memberlite-elements branch in so you can still work from that branch. All of the new updates for Memberlite 4.0 are on the memberlite-elements branch.

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/memberlite/commit/637c77b4185165985033ad5d5704ba0771b87cb8
