### ISSUE TITLE
Test Memberlite Guide "Install" links on multisite.

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/memberlite#91]
On multisite, the "Install Now" links take you to a "you don't have permission" page. We should handle multisite environments more cleanly for this Memberlite Guide admin page.

Also test that installed plugins show an "activate" link instead of the "Install Now" button.

**Comment by ideadude** [comment]
Confirmed that if the plugins are "installed" on the network, the links on the welcome page say "install" and throw an error. They should say "activate" instead.
