### ISSUE TITLE
Changing the action color in the customizer doesn't update some elements until the page is reloaded

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/memberlite#96]
Open the customizer, go to Colors, change the action color. The back to top button in the lower right and post comment buttons aren't updated to use the new action color until the page is refreshed.

We should make sure the JS is wired up properly for this field.

**Comment by ideadude** [comment]
This was happening in the Memberlite Dark theme WIP. In the core theme the back to top button doesn't use the action color. So figure this out with MLD.

**Comment by kimcoleman** [comment]
Correct - a child theme that wanted to apply the "action" color to additional buttons would need to update or filter (may need new filter in Memberite) the global in defaults.php for color_action_background_elements (https://github.com/strangerstudios/memberlite/blob/dev/inc/defaults.php#L41).

Existing JavaScript in customizer.js should then automatically bind the elements per https://github.com/strangerstudios/memberlite/blob/dev/js/customizer.js#L202-L215.

**Comment by kimcoleman** [comment]
This should be fixed in the child theme if needed to adjust those bg colors.
