### ISSUE TITLE
When you return to Cutomizer -> Colors the color scheme is set to Default instead of Custom

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/memberlite#97]
Go to Customizer -> Colors. Set a custom color scheme.

Close the Customizer. Open it again.

Go to Customizer -> Colors. The color scheme dropdown is set to default instead of custom.

**Comment by kimcoleman** [comment]
"Custom" wasn't a valid option when sanitizing the color schemes so it wouldn't allow it. Always falls back to "default". I updated the possible choices to allow "custom" when sanitizing the schemes and now its working.

**Comment by kimcoleman** [comment]
Done in https://github.com/strangerstudios/memberlite/commit/1ff9e63c05ec516497cbda25e2b23de0575f8150
